#!/usr/bin/env node
/*jslint node: true */
var fs = require('fs');
var optimist = require('optimist')
  .usage([
    'Usage: yaml2sql < tabular_data.yaml',
    '',
    'Convert a yaml file to SQL INSERT statements',
    '',
    'This is handy if you have a yaml file with table names as keys, where',
    "each table's value is a list of objects, where those objects are rows",
    'to be inserted into that table. This lets you run something like:',
    '    <my_data.yaml yaml2sql | psql my_database',
  ].join('\n'))
  .describe({
    help: 'print this help message',
    verbose: 'print more output',
  })
  .boolean(['help', 'verbose'])
  .alias({verbose: 'v'});

var argv = optimist.argv;

if (argv.help) {
  optimist.showHelp();
}
else if (process.stdin.isTTY) {
  throw new Error('YAML must be piped in on STDIN');
}
else {
  var yaml2sql = require('./');
  var chunks = [];
  process.stdin.on('data', function(chunk) {
    chunks.push(chunk);
  });
  process.stdin.on('end', function() {
    var yaml = Buffer.concat(chunks);
    var sql = yaml2sql(yaml);
    console.log(sql);
  });
}
